// Investimentos
document.write('<script src="geoJson/geoJsonJS/investimentos/investimentos_final.js"></script>')

// estradas
document.write('<script src="geoJson/geoJsonJS/estradas/eixo_guanduba.js"></script>')
document.write('<script src="geoJson/geoJsonJS/estradas/eixo_producao.js"></script>')
document.write('<script src="geoJson/geoJsonJS/estradas/RN_233.js"></script>')
document.write('<script src="geoJson/geoJsonJS/estradas/RN_011.js"></script>')
document.write('<script src="geoJson/geoJsonJS/estradas/RN_016.js"></script>')
document.write('<script src="geoJson/geoJsonJS/estradas/RN_063.js"></script>')
document.write('<script src="geoJson/geoJsonJS/estradas/RN_087.js"></script>')
document.write('<script src="geoJson/geoJsonJS/estradas/RN_118.js"></script>')
document.write('<script src="geoJson/geoJsonJS/estradas/RN_160.js"></script>')
document.write('<script src="geoJson/geoJsonJS/estradas/RN_307.js"></script>')
document.write('<script src="geoJson/geoJsonJS/estradas/rodovias_federais.js"></script>')
document.write('<script src="geoJson/geoJsonJS/estradas/rodovias_estaduais.js"></script>')
document.write('<script src="geoJson/geoJsonJS/estradas/estradas_DER/projetos_DER_II.js"></script>')
document.write('<script src="geoJson/geoJsonJS/estradas/estradas_DER/projetos_DER_III_A.js"></script>')
document.write('<script src="geoJson/geoJsonJS/estradas/estradas_DER/projetos_DER_III_B.js"></script>')
document.write('<script src="geoJson/geoJsonJS/estradas/estradas_DER/projetos_DER_I_A.js"></script>')
document.write('<script src="geoJson/geoJsonJS/estradas/estradas_DER/projetos_DER_I_B.js"></script>')
document.write('<script src="geoJson/geoJsonJS/estradas/estradas_DER/projetos_DER_V.js"></script>')
document.write('<script src="geoJson/geoJsonJS/estradas/estradas_DER/projetos_DER_VI.js"></script>')
// outras importações
document.write('<script src="geoJson/geoJsonJS/RN_Municipios_2021.js"></script>')
document.write('<script src="geoJson/geoJsonJS/Territorios.js"></script>')
document.write('<script src="geoJson/geoJsonJS/semiarido/semiarido.js"></script>')
document.write('<script src="geoJson/geoJsonJS/semiarido/semiarido_RN_municipios.js"></script>')
document.write('<script src="geoJson/geoJsonJS/semiarido/semiarido_territorio.js"></script>')
document.write('<script src="geoJson/geoJsonJS/Distrito_cor.js"></script>')
document.write('<script src="geoJson/geoJsonJS/Distrito_limitacao.js"></script>')

document.write('<script src="geoJson/geoJsonJS/brasil/brasil.js"></script>')