var leite_e_derivados = {
    "type": "FeatureCollection",
    "name": "leite_e_derivados",
    "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::4674" } },
    "features": [
    { "type": "Feature", "properties": { "Id SMI da MI": "1989", "UES": "UES-SAPE", "Município": "PEDRA PRETA", "Território": "Sertão Central Litoral Norte", "Tipologia": "Subprojetos de Iniciativas de Negócios Sustentáveis de Inclusão Produtiva", "Subtipologia": "Leite e derivados", "Categoria": "Fábrica de Laticínio", "Subcategoria": "Equipamentos para processamento da produção, Construção de unidade de produção", "norte": "-5.5807", "leste": "-36.1026" }, "geometry": { "type": "Point", "coordinates": [ -36.1026, -5.5807 ] } },
    { "type": "Feature", "properties": { "Id SMI da MI": "1991", "UES": "UES-SAPE", "Município": "UMARIZAL", "Território": "Sertão do Apodi", "Tipologia": "Subprojetos de Iniciativas de Negócios Sustentáveis de Inclusão Produtiva", "Subtipologia": "Leite e derivados", "Categoria": "Fábrica de Laticínio", "Subcategoria": "Queijeiras", "norte": "-5.9811", "leste": "-37.8159" }, "geometry": { "type": "Point", "coordinates": [ -37.8159, -5.9811 ] } },
    { "type": "Feature", "properties": { "Id SMI da MI": "1992", "UES": "UES-SAPE", "Município": "SÃO JOSÉ DE MIPIBU", "Território": "Agreste Litoral Sul", "Tipologia": "Subprojetos de Iniciativas de Negócios Sustentáveis de Inclusão Produtiva", "Subtipologia": "Leite e derivados", "Categoria": "Fábrica de Laticínio", "Subcategoria": "Queijeiras, Equipamentos para processamento da produção, Veículo", "norte": "-6.1055", "leste": "-35.277" }, "geometry": { "type": "Point", "coordinates": [ -35.277, -6.1055 ] } },
    { "type": "Feature", "properties": { "Id SMI da MI": "1993", "UES": "UES-SAPE", "Município": "AÇU", "Território": "Açu-Mossoró", "Tipologia": "Subprojetos de Iniciativas de Negócios Sustentáveis de Inclusão Produtiva", "Subtipologia": "Leite e derivados", "Categoria": "Fábrica de Laticínio", "Subcategoria": "Equipamentos para processamento da produção, Construção de unidade de produção", "norte": "-5.5148", "leste": "-36.9153" }, "geometry": { "type": "Point", "coordinates": [ -36.9153, -5.5148 ] } },
    { "type": "Feature", "properties": { "Id SMI da MI": "1555", "UES": "UES-SAPE", "Município": "CARAÚBAS", "Território": "Sertão do Apodi", "Tipologia": "Subprojetos de Iniciativas de Negócios Sustentáveis de Inclusão Produtiva", "Subtipologia": "Leite e derivados", "Categoria": "Unidade de Beneficiamento de Leite", "Subcategoria": "Ampliação e ou Reforma de Prédio, Equipamentos de processamento", "norte": "-5.3826", "leste": "-37.4027" }, "geometry": { "type": "Point", "coordinates": [ -37.4027, -5.3826 ] } },
    { "type": "Feature", "properties": { "Id SMI da MI": "2024", "UES": "UES-SAPE", "Município": "SÃO JOÃO DO SABUGI", "Território": "Seridó", "Tipologia": "Subprojetos de Iniciativas de Negócios Sustentáveis de Inclusão Produtiva", "Subtipologia": "Leite e derivados", "Categoria": "Fábrica de Laticínio", "Subcategoria": "Queijeiras, Equipamentos para processamento da produção, Construção de unidade de produção, Veículo", "norte": "-6.1302", "leste": "-36.4104" }, "geometry": { "type": "Point", "coordinates": [ -36.4104, -6.1302 ] } },
    { "type": "Feature", "properties": { "Id SMI da MI": "2040", "UES": "UES-SAPE", "Município": "PARELHAS", "Território": "Seridó", "Tipologia": "Subprojetos de Iniciativas de Negócios Sustentáveis de Inclusão Produtiva", "Subtipologia": "Leite e derivados", "Categoria": "Fábrica de Laticínio", "Subcategoria": "Queijeiras, Equipamentos para processamento da produção, Ampliação/reforma da unidade de produção, Construção de unidade de produção, Veículo", "norte": "-6.5994", "leste": "-36.5772" }, "geometry": { "type": "Point", "coordinates": [ -36.5772, -6.5994 ] } },
    { "type": "Feature", "properties": { "Id SMI da MI": "2043", "UES": "UES-SAPE", "Município": "CAMPO GRANDE", "Território": "Sertão do Apodi", "Tipologia": "Subprojetos de Iniciativas de Negócios Sustentáveis de Inclusão Produtiva", "Subtipologia": "Leite e derivados", "Categoria": "Fábrica de Laticínio", "Subcategoria": "Queijeiras, Equipamentos para processamento da produção, Construção de unidade de produção", "norte": "-5.7936", "leste": "-37.2351" }, "geometry": { "type": "Point", "coordinates": [ -37.2351, -5.7936 ] } },
    { "type": "Feature", "properties": { "Id SMI da MI": "2048", "UES": "UES-SAPE", "Município": "RIACHUELO", "Território": "Potengi", "Tipologia": "Subprojetos de Iniciativas de Negócios Sustentáveis de Inclusão Produtiva", "Subtipologia": "Leite e derivados", "Categoria": "Fábrica de Laticínio", "Subcategoria": "Equipamentos para processamento da produção, Construção de unidade de produção, Veículo", "norte": "-5.8935", "leste": "-35.7338" }, "geometry": { "type": "Point", "coordinates": [ -35.7338, -5.8935 ] } },
    { "type": "Feature", "properties": { "Id SMI da MI": "1560", "UES": "UES-SAPE", "Município": "AFONSO BEZERRA", "Território": "Sertão Central Litoral Norte", "Tipologia": "Subprojetos de Iniciativas de Negócios Sustentáveis de Inclusão Produtiva", "Subtipologia": "Leite e derivados", "Categoria": "Unidade de Beneficiamento de Leite", "Subcategoria": "Ampliação e ou Reforma de Prédio, Equipamentos de processamento", "norte": "-5.5001", "leste": "-36.504" }, "geometry": { "type": "Point", "coordinates": [ -36.504, -5.5001 ] } },
    { "type": "Feature", "properties": { "Id SMI da MI": "1580", "UES": "UES-SAPE", "Município": "PEDRO VELHO", "Território": "Agreste Litoral Sul", "Tipologia": "Subprojetos de Iniciativas de Negócios Sustentáveis de Inclusão Produtiva", "Subtipologia": "Leite e derivados", "Categoria": "Fábrica de Laticínio", "Subcategoria": "Equipamentos para processamento da produção, Construção de unidade de produção, Veículo", "norte": "-6.4517", "leste": "-35.2579" }, "geometry": { "type": "Point", "coordinates": [ -35.2579, -6.4517 ] } },
    { "type": "Feature", "properties": { "Id SMI da MI": "1585", "UES": "UES-SAPE", "Município": "ANGICOS", "Território": "Sertão Central Litoral Norte", "Tipologia": "Subprojetos de Iniciativas de Negócios Sustentáveis de Inclusão Produtiva", "Subtipologia": "Leite e derivados", "Categoria": "Usina solar fotovoltaica", "Subcategoria": "Laticínio", "norte": "-5.6712", "leste": "-36.5978" }, "geometry": { "type": "Point", "coordinates": [ -36.5978, -5.6712 ] } },
    { "type": "Feature", "properties": { "Id SMI da MI": "1598", "UES": "UES-SAPE", "Município": "CURRAIS NOVOS", "Território": "Seridó", "Tipologia": "Subprojetos de Iniciativas de Negócios Sustentáveis de Inclusão Produtiva", "Subtipologia": "Leite e derivados", "Categoria": "Cozinha Industrial", "Subcategoria": "Equipamentos para produção de bolos e doces, Ampliação e ou reforma da cozinha", "norte": "-6.104", "leste": "-36.3439" }, "geometry": { "type": "Point", "coordinates": [ -36.3439, -6.104 ] } },
    { "type": "Feature", "properties": { "Id SMI da MI": "1636", "UES": "UES-SAPE", "Município": "SANTANA DO MATOS", "Território": "Seridó", "Tipologia": "Subprojetos de Iniciativas de Negócios Sustentáveis de Inclusão Produtiva", "Subtipologia": "Leite e derivados", "Categoria": "Fábrica de Laticínio", "Subcategoria": "Queijeiras", "norte": "-5.7999", "leste": "-36.6979" }, "geometry": { "type": "Point", "coordinates": [ -36.6979, -5.7999 ] } }
    ]
    }
    