let Fruticultura_irrigada = {
"type": "FeatureCollection",
"name": "Fruticultura_irrigada",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Id SMI da MI": 1544, "UES": "UES-SAPE", "Município": "MOSSORÓ", "Território": "Açu-Mossoró", "Tipologia": "Subprojetos de Iniciativa de Negócios Sustentáveis - Piloto da Agricultura Irrigada", "Subtipologia": "Fruticultura Irrigada", "Categoria": "Fruticultura Irrigada", "Subcategoria": null, "Nº do Processo do Convênio": "73299/2016-1", "Nº da MI": null, "Nº do Edital": null, "Entidade Proponente": null, "Seleção": null, "Cadeira Produtiva": "Fruticultura Irrigada", "Atividade Produtiva": null, "Data de Início da vigência (data de incio de execuçao do subprojeto)": null, "Data de Fim da vigência (data de encerramento de execução do subprojeto)": null, "Ano inicial da operação do empreedimento": null, "Valor Total do Convênio": null, "Valor BIRD": null, "Valor da Contrapartida": null, "Total de Beneficiários Confirmados": null, "Beneficiárias Mulheres Confirmadas": null, "Beneficiários Jovens Confirmados": null, "Entidade Presidida por Mulher": null, "Entidade Liderada por Mulher": null, "Grupo Tradicional Comunidade": null }, "geometry": { "type": "Point", "coordinates": [ -37.4552, -5.0027 ] } },
{ "type": "Feature", "properties": { "Id SMI da MI": 1545, "UES": "UES-SAPE", "Município": "MOSSORÓ", "Território": "Açu-Mossoró", "Tipologia": "Subprojetos de Iniciativa de Negócios Sustentáveis - Piloto da Agricultura Irrigada", "Subtipologia": "Fruticultura Irrigada", "Categoria": "Fruticultura Irrigada", "Subcategoria": null, "Nº do Processo do Convênio": "73309/2016-1", "Nº da MI": null, "Nº do Edital": null, "Entidade Proponente": null, "Seleção": null, "Cadeira Produtiva": "Fruticultura Irrigada", "Atividade Produtiva": null, "Data de Início da vigência (data de incio de execuçao do subprojeto)": null, "Data de Fim da vigência (data de encerramento de execução do subprojeto)": null, "Ano inicial da operação do empreedimento": null, "Valor Total do Convênio": null, "Valor BIRD": null, "Valor da Contrapartida": null, "Total de Beneficiários Confirmados": null, "Beneficiárias Mulheres Confirmadas": null, "Beneficiários Jovens Confirmados": null, "Entidade Presidida por Mulher": null, "Entidade Liderada por Mulher": null, "Grupo Tradicional Comunidade": null }, "geometry": { "type": "Point", "coordinates": [ -37.3626, -5.0342 ] } }
]
}
