let Reciclagem = {
"type": "FeatureCollection",
"name": "Reciclagem",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Id SMI da MI": 1050, "UES": "UES-SETHAS", "Município": "PARELHAS", "Território": "Seridó", "Tipologia": "Subprojetos de Empreendimentos Econômicos e Solidários da Agricultura Familiar", "Subtipologia": "Empreendimento Coletivo", "Categoria": "Reciclagem", "Subcategoria": "Triagem e beneficiamento de materiais recicláveis", "Nº do Processo do Convênio": "3075/2016-1", "Nº da MI": 295, "Nº do Edital": "2/2014", "Entidade Proponente": "ASSOCIACAO DE CATADORES DE MATERIAIS RECICLAVEIS DE PARELHAS (16.914.133/0001-03)", "Seleção": "Não", "Cadeira Produtiva": "Reciclagem", "Atividade Produtiva": "Triagem e beneficiamento de materiais recicláveis", "Data de Início da vigência (data de incio de execuçao do subprojeto)": "13/11/2017", "Data de Fim da vigência (data de encerramento de execução do subprojeto)": "10/11/2020", "Ano inicial da operação do empreedimento": 2021, "Valor Total do Convênio": 407069.59, "Valor BIRD": 339224.66, "Valor da Contrapartida": 67844.93, "Total de Beneficiários Confirmados": 8, "Beneficiárias Mulheres Confirmadas": 7, "Beneficiários Jovens Confirmados": 2, "Entidade Presidida por Mulher": "Não", "Entidade Liderada por Mulher": "Não", "Grupo Tradicional Comunidade": "Outros: Comunidade Urbana" }, "geometry": { "type": "Point", "coordinates": [ -36.6612, -6.6951 ] } },
{ "type": "Feature", "properties": { "Id SMI da MI": 1343, "UES": "UES-SETHAS", "Município": "CAICÓ", "Território": "Seridó", "Tipologia": "Subprojetos de Empreendimentos Econômicos e Solidários da Agricultura Familiar", "Subtipologia": "Empreendimento Coletivo", "Categoria": "Reciclagem", "Subcategoria": "Triagem e beneficiamento de materiais recicláveis", "Nº do Processo do Convênio": "2070/2016-7", "Nº da MI": 378, "Nº do Edital": "2/2014", "Entidade Proponente": "ASSOCIACAO DE CATADORES DE MATERIAIS RECICLAVEIS DE CAICO(15.435.285/0001-60)", "Seleção": "Não", "Cadeira Produtiva": "Reciclagem", "Atividade Produtiva": "Triagem e beneficiamento de materiais recicláveis", "Data de Início da vigência (data de incio de execuçao do subprojeto)": "27/12/2017", "Data de Fim da vigência (data de encerramento de execução do subprojeto)": "11/12/2020", "Ano inicial da operação do empreedimento": 2021, "Valor Total do Convênio": 395681.52, "Valor BIRD": 329734.6, "Valor da Contrapartida": 65946.92, "Total de Beneficiários Confirmados": 9, "Beneficiárias Mulheres Confirmadas": 6, "Beneficiários Jovens Confirmados": 2, "Entidade Presidida por Mulher": "Não", "Entidade Liderada por Mulher": "Não", "Grupo Tradicional Comunidade": "Outros: Comunidade Urbana" }, "geometry": { "type": "Point", "coordinates": [ -37.1131, -6.4555 ] } }
]
}
