let Unidade_de_comercializacao = {
"type": "FeatureCollection",
"name": "Unidade_de_comercializacao",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Id SMI da MI": 680, "UES": "UES-SETHAS", "Município": "PILÕES", "Território": "Alto Oeste", "Tipologia": "Subprojetos de Empreendimentos Econômicos e Solidários da Agricultura Familiar", "Subtipologia": "Empreendimento Coletivo", "Categoria": "UNIDADE DE COMERCIALIZAÇÃO", "Subcategoria": "MÁQUINAS E EQUIPAMENTOS, INSUMOS, OBRAS", "Nº do Processo do Convênio": "1041/2016-9", "Nº da MI": 184, "Nº do Edital": "2/2014", "Entidade Proponente": "ASSOCIACAO COM DOS PDR DO ST GLORIA NO MUN DE PILOES (00.892.996/0001-97)", "Seleção": "Não", "Cadeira Produtiva": "UNIDADE DE COMERCIALIZAÇÃO", "Atividade Produtiva": "UNIDADE DE COMERCIALIZAÇÃO", "Data de Início da vigência (data de incio de execuçao do subprojeto)": "18/07/2017", "Data de Fim da vigência (data de encerramento de execução do subprojeto)": "31/12/2020", "Ano inicial da operação do empreedimento": 2021, "Valor Total do Convênio": 299727.82, "Valor BIRD": 252776.65, "Valor da Contrapartida": 46951.17, "Total de Beneficiários Confirmados": 20, "Beneficiárias Mulheres Confirmadas": 9, "Beneficiários Jovens Confirmados": 2, "Entidade Presidida por Mulher": "Não", "Entidade Liderada por Mulher": "Não", "Grupo Tradicional Comunidade": "Outros: COMUNIDADE RURAL" }, "geometry": { "type": "Point", "coordinates": [ -38.0236, -6.1607 ] } },
{ "type": "Feature", "properties": { "Id SMI da MI": 770, "UES": "UES-SETHAS", "Município": "UPANEMA", "Território": "Sertão do Apodi", "Tipologia": "Subprojetos de Empreendimentos Econômicos e Solidários da Agricultura Familiar", "Subtipologia": "Empreendimento Coletivo", "Categoria": "UNIDADE DE COMERCIALIZAÇÃO", "Subcategoria": "MÁQUINAS E EQUIPAMENTOS, INSUMOS, OBRAS", "Nº do Processo do Convênio": "4056/2016-1", "Nº da MI": 217, "Nº do Edital": "2/2014", "Entidade Proponente": "ASSOCIAÇÃO DOS PRODUTORES E FEIRANTES DA AGRICULTURA FAMILIAR DE UPANEMA (12.231.671/0001-42)", "Seleção": "Não", "Cadeira Produtiva": "UNIDADE DE COMERCIALIZAÇÃO", "Atividade Produtiva": "UNIDADE DE COMERCIALIZAÇÃO", "Data de Início da vigência (data de incio de execuçao do subprojeto)": "17/08/2017", "Data de Fim da vigência (data de encerramento de execução do subprojeto)": "14/09/2020", "Ano inicial da operação do empreedimento": 2021, "Valor Total do Convênio": 538230.19, "Valor BIRD": 438230.19, "Valor da Contrapartida": 100000.0, "Total de Beneficiários Confirmados": 15, "Beneficiárias Mulheres Confirmadas": 8, "Beneficiários Jovens Confirmados": 1, "Entidade Presidida por Mulher": "Não", "Entidade Liderada por Mulher": "Não", "Grupo Tradicional Comunidade": "Outros: Comunidades e Assentamentos rurais" }, "geometry": { "type": "Point", "coordinates": [ -37.2578, -5.6414 ] } }
]
}
